name: Release Hein

on:
  push:
    tags:
      - "hein_*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn --cwd packages/hein
      - run: yarn --cwd packages/hein run build
      - run: yarn --cwd packages/hein run lint
      - run: yarn --cwd packages/hein run test
      - run: yarn --cwd packages/hein release --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
