name: Release hein

on:
  push:
    tags:
      - "hein@*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn --cwd packages/hein run lint
      - run: yarn build
      - run: yarn --cwd packages/hein publish --tag=alpha --non-interactive
