name: Release eslint-config-hein

on:
  push:
    tags:
      - "eslint-config-hein@*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn --cwd packages/eslint-config-hein
      - run: yarn --cwd packages/eslint-config-hein run lint
      - run: yarn --cwd packages/eslint-config-hein publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
