name: Release hein-plugin-supertest

on:
  push:
    tags:
      - "hein-plugin-supertest@*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn --cwd packages/hein-plugin-supertest run lint
      - run: yarn build
      - run: yarn --cwd packages/hein-plugin-supertest publish --non-interactive
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
