name: Release hein-plugin-sinon

on:
  push:
    tags:
      - "hein-plugin-sinon@*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn --cwd packages/hein-plugin-sinon
      - run: yarn --cwd packages/hein-plugin-sinon run lint
      - run: yarn --cwd packages/hein-plugin-sinon build
      - run: yarn --cwd packages/hein-plugin-sinon publish --non-interactive
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
